universe = vanilla
Executable = /afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/submit.sh
+JobFlavour="espresso"
when_to_transfer_output = ON_EXIT
transfer_input_files = /afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/ntuple_mc_2018_cfg.py, /afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/submit.sh
transfer_output_files = MonoNtuple2018_MC_1000_$(Process).root
Output =/afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/condor/output/log_job_$(Process)
Error  =/afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/condor/errors/log_job_$(Process)
Log    =/afs/cern.ch/user/l/lshih/CMSSW_10_6_23/src/condor/stdout/log_job_$(Process)
getenv=true
RequestCpus = 4

max_retries = 1
Arguments  = $(remoteFILE) $(Process)
Queue remoteFILE from remoteFileList.txt
